### ISSUE TITLE
[MSKINS-264] dark mode?

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-fluido-skin#255]
**[Stephen Buergler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sixcorners)** opened **[MSKINS-264](https://issues.apache.org/jira/browse/MSKINS-264?redirect=false)** and commented

Think it would be possible or a good idea to add a dark mode?
In css there are three things that can be used to implement a dark mode:
https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme
The color-scheme attribute which changes a bunch of the defaults:

```css
:root {
  color-scheme: light dark;
}
```

The light-dark function:

```css
.element {
  color: light-dark(black, white);
  background-color: light-dark(white, black);
}
```

And media queries:

```css
@media (prefers-color-scheme: light) {
  .element {
    color: black;
    background-color: white;
  }
}

@media (prefers-color-scheme: dark) {
  .element {
    color: white;
    background-color: black;
  }
}
```

Then you just set it in your OS and your browser switches all the colors.

---
No further details from [MSKINS-264](https://issues.apache.org/jira/browse/MSKINS-264?redirect=false)
